# fly.toml app configuration file generated for taskwizard on 2023-09-04T19:35:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "taskwizard"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
